// Generated 23 Feb 2023 14:39 - Singular Systems Object Generator Version 2.2.694
//<auto-generated/>
using System;
using Csla;
using Csla.Serialization;
using Csla.Data;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Singular;
using System.Data;
using System.Data.SqlClient;


namespace MELib.Carts
{
    [Serializable]
    public class CartItemList
     : SingularBusinessListBase<CartItemList, CartItem>
    {
        #region " Business Methods "

        public CartItem GetItem(int CartItemID)
        {
            foreach (CartItem child in this)
            {
                if (child.CartItemID == CartItemID)
                {
                    return child;
                }
            }
            return null;
        }

        public override string ToString()
        {
            return "Cart Items";
        }

        #endregion

        #region " Data Access "

        [Serializable]
        public class Criteria
          : CriteriaBase<Criteria>
        {
            public int? ProductId;
            public int? userId;
            public Criteria()
            {
            }
            public Criteria(int? ProductId)
            {
                this.ProductId = ProductId;
            }
            public Criteria(int? ProductId, int? userId)
            {
                this.ProductId = ProductId;
                this.userId = userId;
            }

        }

        public static CartItemList NewCartItemList()
        {
            return new CartItemList();
        }

        public CartItemList()
        {
            // must have parameter-less constructor
        }

        public static CartItemList GetCartItemList()
        {
            return DataPortal.Fetch<CartItemList>(new Criteria());
        }
        public static CartItemList GetCartItemList(int? ProductId)
        {
            return DataPortal.Fetch<CartItemList>(new Criteria { ProductId = ProductId });
        }

        public static CartItemList GetCartItemList(int? ProductId,int? userId)
        {
            return DataPortal.Fetch<CartItemList>(new Criteria { ProductId = ProductId, userId = userId});
        }

        protected void Fetch(SafeDataReader sdr)
        {
            this.RaiseListChangedEvents = false;
            while (sdr.Read())
            {
                this.Add(CartItem.GetCartItem(sdr));
            }
            this.RaiseListChangedEvents = true;
        }

        protected override void DataPortal_Fetch(Object criteria)
        {
            Criteria crit = (Criteria)criteria;
            using (SqlConnection cn = new SqlConnection(Singular.Settings.ConnectionString))
            {
                cn.Open();
                try
                {
                    using (SqlCommand cm = cn.CreateCommand())
                    {
                        cm.CommandType = CommandType.StoredProcedure;
                        cm.CommandText = "GetProcs.getCartItemList";
                        cm.Parameters.AddWithValue("@ProductId", Singular.Misc.NothingDBNull(crit.ProductId));


                        using (SafeDataReader sdr = new SafeDataReader(cm.ExecuteReader()))
                        {
                            Fetch(sdr);
                        }
                    }
                }
                finally
                {
                    cn.Close();
                }
            }
        }

        #endregion

    }

}