// Generated 04 Mar 2023 16:54 - Singular Systems Object Generator Version 2.2.694
//<auto-generated/>
using System;
using Csla;
using Csla.Serialization;
using Csla.Data;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Singular;
using System.Data;
using System.Data.SqlClient;


namespace MELib.Orders
{
    [Serializable]
    public class OrderType
     : SingularBusinessBase<OrderType>
    {
        #region " Properties and Methods "

        #region " Properties "

        public static PropertyInfo<int> OrderTypeIdProperty = RegisterProperty<int>(c => c.OrderTypeId, "ID", 0);
        /// <summary>
        /// Gets the ID value
        /// </summary>
        [Display(AutoGenerateField = false), Key]
        public int OrderTypeId
        {
            get { return GetProperty(OrderTypeIdProperty); }
        }

        public static PropertyInfo<String> OrderNameProperty = RegisterProperty<String>(c => c.OrderName, "Order Name", "");
        /// <summary>
        /// Gets and sets the Order Name value
        /// </summary>
        [Display(Name = "Order Name", Description = ""),
        StringLength(50, ErrorMessage = "Order Name cannot be more than 50 characters")]
        public String OrderName
        {
            get { return GetProperty(OrderNameProperty); }
            set { SetProperty(OrderNameProperty, value); }
        }

        public static PropertyInfo<Decimal> amountProperty = RegisterProperty<Decimal>(c => c.amount, "Amount", 0D);
        /// <summary>
        /// Gets and sets the Amount value
        /// </summary>
        [Display(Name = "Amount", Description = ""),
        Required(ErrorMessage = "Amount required")]
        public Decimal amount
        {
            get { return GetProperty(amountProperty); }
            set { SetProperty(amountProperty, value); }
        }

        public static PropertyInfo<DateTime?> DeletedDateProperty = RegisterProperty<DateTime?>(c => c.DeletedDate, "Deleted Date");
        /// <summary>
        /// Gets and sets the Deleted Date value
        /// </summary>
        [Display(Name = "Deleted Date", Description = "")]
        public DateTime? DeletedDate
        {
            get
            {
                return GetProperty(DeletedDateProperty);
            }
            set
            {
                SetProperty(DeletedDateProperty, value);
            }
        }

        public static PropertyInfo<DateTime?> DeletedByProperty = RegisterProperty<DateTime?>(c => c.DeletedBy, "Deleted By");
        /// <summary>
        /// Gets and sets the Deleted By value
        /// </summary>
        [Display(Name = "Deleted By", Description = "")]
        public DateTime? DeletedBy
        {
            get
            {
                return GetProperty(DeletedByProperty);
            }
            set
            {
                SetProperty(DeletedByProperty, value);
            }
        }

        public static PropertyInfo<SmartDate> ModifiedDateProperty = RegisterProperty<SmartDate>(c => c.ModifiedDate, "Modified Date", new SmartDate(DateTime.Now));
        /// <summary>
        /// Gets the Modified Date value
        /// </summary>
        [Display(AutoGenerateField = false)]
        public SmartDate ModifiedDate
        {
            get { return GetProperty(ModifiedDateProperty); }
        }

        public static PropertyInfo<int> ModifiedByProperty = RegisterProperty<int>(c => c.ModifiedBy, "Modified By", 0);
        /// <summary>
        /// Gets the Modified By value
        /// </summary>
        [Display(AutoGenerateField = false)]
        public int ModifiedBy
        {
            get { return GetProperty(ModifiedByProperty); }
        }

        public static PropertyInfo<SmartDate> CreatedDateProperty = RegisterProperty<SmartDate>(c => c.CreatedDate, "Created Date", new SmartDate(DateTime.Now));
        /// <summary>
        /// Gets the Created Date value
        /// </summary>
        [Display(AutoGenerateField = false)]
        public SmartDate CreatedDate
        {
            get { return GetProperty(CreatedDateProperty); }
        }

        public static PropertyInfo<int> CreatedByProperty = RegisterProperty<int>(c => c.CreatedBy, "Created By", 0);
        /// <summary>
        /// Gets the Created By value
        /// </summary>
        [Display(AutoGenerateField = false)]
        public int CreatedBy
        {
            get { return GetProperty(CreatedByProperty); }
        }

        #endregion

        #region " Methods "

        protected override object GetIdValue()
        {
            return GetProperty(OrderTypeIdProperty);
        }

        public override string ToString()
        {
            if (this.OrderName.Length == 0)
            {
                if (this.IsNew)
                {
                    return String.Format("New {0}", "Order Type");
                }
                else
                {
                    return String.Format("Blank {0}", "Order Type");
                }
            }
            else
            {
                return this.OrderName;
            }
        }

        #endregion

        #endregion

        #region " Validation Rules "

        protected override void AddBusinessRules()
        {
            base.AddBusinessRules();
        }

        #endregion

        #region " Data Access & Factory Methods "

        protected override void OnCreate()
        {
            // This is called when a new object is created
            // Set any variables here, not in the constructor or NewOrderType() method.
        }

        public static OrderType NewOrderType()
        {
            return DataPortal.CreateChild<OrderType>();
        }

        public OrderType()
        {
            MarkAsChild();
        }

        internal static OrderType GetOrderType(SafeDataReader dr)
        {
            var o = new OrderType();
            o.Fetch(dr);
            return o;
        }

        protected void Fetch(SafeDataReader sdr)
        {
            using (BypassPropertyChecks)
            {
                int i = 0;
                LoadProperty(OrderTypeIdProperty, sdr.GetInt32(i++));
                LoadProperty(OrderNameProperty, sdr.GetString(i++));
                LoadProperty(amountProperty, sdr.GetDecimal(i++));
                LoadProperty(DeletedDateProperty, sdr.GetValue(i++));
                LoadProperty(DeletedByProperty, sdr.GetValue(i++));
                LoadProperty(ModifiedDateProperty, sdr.GetSmartDate(i++));
                LoadProperty(ModifiedByProperty, sdr.GetInt32(i++));
                LoadProperty(CreatedDateProperty, sdr.GetSmartDate(i++));
                LoadProperty(CreatedByProperty, sdr.GetInt32(i++));
            }

            MarkAsChild();
            MarkOld();
            BusinessRules.CheckRules();
        }

        protected override Action<SqlCommand> SetupSaveCommand(SqlCommand cm)
        {
            LoadProperty(ModifiedByProperty, Settings.CurrentUser.UserID);

            AddPrimaryKeyParam(cm, OrderTypeIdProperty);

            cm.Parameters.AddWithValue("@OrderName", GetProperty(OrderNameProperty));
            cm.Parameters.AddWithValue("@amount", GetProperty(amountProperty));
            cm.Parameters.AddWithValue("@DeletedDate", Singular.Misc.NothingDBNull(DeletedDate));
            cm.Parameters.AddWithValue("@DeletedBy", Singular.Misc.NothingDBNull(DeletedBy));
            cm.Parameters.AddWithValue("@ModifiedBy", GetProperty(ModifiedByProperty));

            return (scm) =>
            {
    // Post Save
    if (this.IsNew)
                {
                    LoadProperty(OrderTypeIdProperty, scm.Parameters["@OrderTypeId"].Value);
                }
            };
        }

        protected override void SaveChildren()
        {
            // No Children
        }

        protected override void SetupDeleteCommand(SqlCommand cm)
        {
            cm.Parameters.AddWithValue("@OrderTypeId", GetProperty(OrderTypeIdProperty));
        }

        #endregion

    }

}