// Generated 04 Mar 2023 16:54 - Singular Systems Object Generator Version 2.2.694
//<auto-generated/>
using System;
using Csla;
using Csla.Serialization;
using Csla.Data;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Singular;
using System.Data;
using System.Data.SqlClient;


namespace MELib.Orders
{
    [Serializable]
    public class OrderTypeList
     : SingularBusinessListBase<OrderTypeList, OrderType>
    {
        #region " Business Methods "

        public OrderType GetItem(int OrderTypeId)
        {
            foreach (OrderType child in this)
            {
                if (child.OrderTypeId == OrderTypeId)
                {
                    return child;
                }
            }
            return null;
        }

        public override string ToString()
        {
            return "Order Types";
        }

        #endregion

        #region " Data Access "

        [Serializable]
        public class Criteria
          : CriteriaBase<Criteria>
        {
            public int? OrderTypeID = null;
            public Criteria()
            {
            }
            public Criteria(int OrderTypeId)
            {
                this.OrderTypeID = OrderTypeId;
            }

        }

        public static OrderTypeList NewOrderTypeList()
        {
            return new OrderTypeList();
        }

        public OrderTypeList()
        {
            // must have parameter-less constructor
        }

        public static OrderTypeList GetOrderTypeList()
        {
            return DataPortal.Fetch<OrderTypeList>(new Criteria());
        }
        public static OrderTypeList GetOrderTypeById(int orderTypeId)
        {
            return DataPortal.Fetch<OrderTypeList>(new Criteria { OrderTypeID = orderTypeId});
        }

        
        protected void Fetch(SafeDataReader sdr)
        {
            this.RaiseListChangedEvents = false;
            while (sdr.Read())
            {
                this.Add(OrderType.GetOrderType(sdr));
            }
            this.RaiseListChangedEvents = true;
        }

        protected override void DataPortal_Fetch(Object criteria)
        {
            Criteria crit = (Criteria)criteria;
            using (SqlConnection cn = new SqlConnection(Singular.Settings.ConnectionString))
            {
                cn.Open();
                try
                {
                    using (SqlCommand cm = cn.CreateCommand())
                    {
                        cm.CommandType = CommandType.StoredProcedure;
                        cm.CommandText = "GetProcs.getOrderTypeList";
                        cm.Parameters.AddWithValue("@OrderTypeID", Singular.Misc.NothingDBNull(crit.OrderTypeID));
                        using (SafeDataReader sdr = new SafeDataReader(cm.ExecuteReader()))
                        {
                            Fetch(sdr);
                        }
                    }
                }
                finally
                {
                    cn.Close();
                }
            }
        }

        #endregion

    }

}