// Generated 04 Mar 2023 11:51 - Singular Systems Object Generator Version 2.2.694
//<auto-generated/>
using System;
using Csla;
using Csla.Serialization;
using Csla.Data;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Singular;
using System.Data;
using System.Data.SqlClient;


namespace MELib.RO
{
    [Serializable]
    public class ROOrderType
     : SingularReadOnlyBase<ROOrderType>
    {
        #region " Properties and Methods "

        #region " Properties "

        public static PropertyInfo<int> OrderTypeIdProperty = RegisterProperty<int>(c => c.OrderTypeId, "ID", 0);
        /// <summary>
        /// Gets the ID value
        /// </summary>
        [Display(AutoGenerateField = false), Key]
        public int OrderTypeId
        {
            get { return GetProperty(OrderTypeIdProperty); }
        }

        public static PropertyInfo<String> OrderNameProperty = RegisterProperty<String>(c => c.OrderName, "Order Name", "");
        /// <summary>
        /// Gets the Order Name value
        /// </summary>
        [Display(Name = "Order Name", Description = "")]
        public String OrderName
        {
            get { return GetProperty(OrderNameProperty); }
        }

        public static PropertyInfo<decimal> amountProperty = RegisterProperty<decimal>(c => c.amount, "Is Active", 0.0);
        /// <summary>
        /// Gets the Is Active value
        /// </summary>
        [Display(Name = "Is Active", Description = "")]
        public decimal amount
        {
            get { return GetProperty(amountProperty); }
        }

        public static PropertyInfo<DateTime?> DeletedDateProperty = RegisterProperty<DateTime?>(c => c.DeletedDate, "Deleted Date");
        /// <summary>
        /// Gets the Deleted Date value
        /// </summary>
        [Display(Name = "Deleted Date", Description = "")]
        public DateTime? DeletedDate
        {
            get
            {
                return GetProperty(DeletedDateProperty);
            }
        }

        public static PropertyInfo<DateTime?> DeletedByProperty = RegisterProperty<DateTime?>(c => c.DeletedBy, "Deleted By");
        /// <summary>
        /// Gets the Deleted By value
        /// </summary>
        [Display(Name = "Deleted By", Description = "")]
        public DateTime? DeletedBy
        {
            get
            {
                return GetProperty(DeletedByProperty);
            }
        }

        public static PropertyInfo<SmartDate> ModifiedDateProperty = RegisterProperty<SmartDate>(c => c.ModifiedDate, "Modified Date", new SmartDate(DateTime.Now));
        /// <summary>
        /// Gets the Modified Date value
        /// </summary>
        [Display(AutoGenerateField = false)]
        public SmartDate ModifiedDate
        {
            get { return GetProperty(ModifiedDateProperty); }
        }

        public static PropertyInfo<int> ModifiedByProperty = RegisterProperty<int>(c => c.ModifiedBy, "Modified By", 0);
        /// <summary>
        /// Gets the Modified By value
        /// </summary>
        [Display(AutoGenerateField = false)]
        public int ModifiedBy
        {
            get { return GetProperty(ModifiedByProperty); }
        }

        public static PropertyInfo<SmartDate> CreatedDateProperty = RegisterProperty<SmartDate>(c => c.CreatedDate, "Created Date", new SmartDate(DateTime.Now));
        /// <summary>
        /// Gets the Created Date value
        /// </summary>
        [Display(AutoGenerateField = false)]
        public SmartDate CreatedDate
        {
            get { return GetProperty(CreatedDateProperty); }
        }

        public static PropertyInfo<int> CreatedByProperty = RegisterProperty<int>(c => c.CreatedBy, "Created By", 0);
        /// <summary>
        /// Gets the Created By value
        /// </summary>
        [Display(AutoGenerateField = false)]
        public int CreatedBy
        {
            get { return GetProperty(CreatedByProperty); }
        }

        #endregion

        #region " Methods "

        protected override object GetIdValue()
        {
            return GetProperty(OrderTypeIdProperty);
        }

        public override string ToString()
        {
            return this.OrderName;
        }

        #endregion

        #endregion

        #region " Data Access & Factory Methods "

        internal static ROOrderType GetROOrderType(SafeDataReader dr)
        {
            var r = new ROOrderType();
            r.Fetch(dr);
            return r;
        }

        protected void Fetch(SafeDataReader sdr)
        {
            int i = 0;
            LoadProperty(OrderTypeIdProperty, sdr.GetInt32(i++));
            LoadProperty(OrderNameProperty, sdr.GetString(i++));
            LoadProperty(amountProperty, sdr.GetDecimal(i++));
            LoadProperty(DeletedDateProperty, sdr.GetValue(i++));
            LoadProperty(DeletedByProperty, sdr.GetValue(i++));
            LoadProperty(ModifiedDateProperty, sdr.GetSmartDate(i++));
            LoadProperty(ModifiedByProperty, sdr.GetInt32(i++));
            LoadProperty(CreatedDateProperty, sdr.GetSmartDate(i++));
            LoadProperty(CreatedByProperty, sdr.GetInt32(i++));
        }

        #endregion

    }

}