// Generated 04 Mar 2023 11:51 - Singular Systems Object Generator Version 2.2.694
//<auto-generated/>
using System;
using Csla;
using Csla.Serialization;
using Csla.Data;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Singular;
using System.Data;
using System.Data.SqlClient;


namespace MELib.RO
{
    [Serializable]
    public class ROOrderTypeList
     : SingularReadOnlyListBase<ROOrderTypeList, ROOrderType>
    {
        #region " Business Methods "

        public ROOrderType GetItem(int OrderTypeId)
        {
            foreach (ROOrderType child in this)
            {
                if (child.OrderTypeId == OrderTypeId)
                {
                    return child;
                }
            }
            return null;
        }

        public override string ToString()
        {
            return "RO Order Types";
        }

        #endregion

        #region " Data Access "

        [Serializable]
        public class Criteria
          : CriteriaBase<Criteria>
        {
            public Criteria()
            {
            }

        }

        public static ROOrderTypeList NewROOrderTypeList()
        {
            return new ROOrderTypeList();
        }

        public ROOrderTypeList()
        {
            // must have parameter-less constructor
        }

        public static ROOrderTypeList GetROOrderTypeList()
        {
            return DataPortal.Fetch<ROOrderTypeList>(new Criteria());
        }

        protected void Fetch(SafeDataReader sdr)
        {
            this.RaiseListChangedEvents = false;
            this.IsReadOnly = false;
            while (sdr.Read())
            {
                this.Add(ROOrderType.GetROOrderType(sdr));
            }
            this.IsReadOnly = true;
            this.RaiseListChangedEvents = true;
        }

        protected override void DataPortal_Fetch(Object criteria)
        {
            Criteria crit = (Criteria)criteria;
            using (SqlConnection cn = new SqlConnection(Singular.Settings.ConnectionString))
            {
                cn.Open();
                try
                {
                    using (SqlCommand cm = cn.CreateCommand())
                    {
                        cm.CommandType = CommandType.StoredProcedure;
                        cm.CommandText = "GetProcs.getROOrderTypeList";
                        using (SafeDataReader sdr = new SafeDataReader(cm.ExecuteReader()))
                        {
                            Fetch(sdr);
                        }
                    }
                }
                finally
                {
                    cn.Close();
                }
            }
        }

        #endregion

    }

}