// Generated 08 Mar 2023 07:23 - Singular Systems Object Generator Version 2.2.694
//<auto-generated/>
using System;
using Csla;
using Csla.Serialization;
using Csla.Data;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Singular;
using System.Data;
using System.Data.SqlClient;


namespace MELib.RO
{
    [Serializable]
    public class OrderDetailList
     : SingularBusinessListBase<OrderDetailList, OrderDetail>
    {
        #region " Business Methods "

        public OrderDetail GetItem(int OrderDetailId)
        {
            foreach (OrderDetail child in this)
            {
                if (child.OrderDetailId == OrderDetailId)
                {
                    return child;
                }
            }
            return null;
        }

        public override string ToString()
        {
            return "Order Details";
        }

        #endregion

        #region " Data Access "

        public static OrderDetailList NewOrderDetailList()
        {
            return new OrderDetailList();
        }

        public OrderDetailList()
        {
            // must have parameter-less constructor
        }

        #endregion

    }

}